-- Optional: seeds the exact same catalog the app used to ship with mock
-- data for (lib/products.ts). Running this keeps the legacy mock orders and
-- customers pages (which reference these product ids) resolving correctly,
-- and gives you a populated storefront immediately. Safe to skip if you'd
-- rather start from an empty catalog and add products via /admin.

insert into public.products (
  id, name, slug, short_description, description, category, price,
  compare_at_price, cost, stock, sku, barcode, images, featured, is_new,
  is_promotion, active, meta_title, meta_description, rating, created_at
)
values
('fone-aether-pro', 'Aether Pro Wireless', 'fone-aether-pro', 'Fone de ouvido premium com cancelamento ativo de ruído, áudio espacial e até 30 horas de bateria.', 'Fone de ouvido premium com cancelamento ativo de ruído, áudio espacial e até 30 horas de bateria. Design em alumínio escovado com acabamento em couro vegano.', 'Fones', 1899, 2199, 1044.45, 24, 'SKU-FONE-AETHER-PRO', null, array['https://picsum.photos/seed/aether-pro-1/900/900', 'https://picsum.photos/seed/aether-pro-2/900/900', 'https://picsum.photos/seed/aether-pro-3/900/900']::text[], true, false, true, true, 'Aether Pro Wireless | Marvel', 'Fone de ouvido premium com cancelamento ativo de ruído, áudio espacial e até 30 horas de bateria. Design em alumínio escovado com acabamento em couro vegan', 4.8, '2026-05-12'::timestamptz),
('fone-nova-buds', 'Nova Buds', 'fone-nova-buds', 'Earbuds compactos com som imersivo, resistência à água IPX4 e estojo de carregamento com autonomia total de 24 horas.', 'Earbuds compactos com som imersivo, resistência à água IPX4 e estojo de carregamento com autonomia total de 24 horas.', 'Fones', 799, null, 439.45, 40, 'SKU-FONE-NOVA-BUDS', null, array['https://picsum.photos/seed/nova-buds-1/900/900', 'https://picsum.photos/seed/nova-buds-2/900/900']::text[], false, true, false, true, 'Nova Buds | Marvel', 'Earbuds compactos com som imersivo, resistência à água IPX4 e estojo de carregamento com autonomia total de 24 horas.', 4.5, '2026-07-20'::timestamptz),
('notebook-vortex-14', 'Vortex 14', 'notebook-vortex-14', 'Notebook ultrafino de 14'''', tela OLED 120Hz, processador de última geração e até 18 horas de bateria.', 'Notebook ultrafino de 14'''', tela OLED 120Hz, processador de última geração e até 18 horas de bateria. Feito para criadores e desenvolvedores.', 'Notebooks', 12999, 14499, 7149.45, 8, 'SKU-NOTEBOOK-VORTEX-14', null, array['https://picsum.photos/seed/vortex-14-1/900/900', 'https://picsum.photos/seed/vortex-14-2/900/900', 'https://picsum.photos/seed/vortex-14-3/900/900']::text[], true, false, true, true, 'Vortex 14 | Marvel', 'Notebook ultrafino de 14'''', tela OLED 120Hz, processador de última geração e até 18 horas de bateria. Feito para criadores e desenvolvedores.', 4.9, '2026-03-02'::timestamptz),
('notebook-slate-air', 'Slate Air', 'notebook-slate-air', 'Leveza extrema com apenas 990g.', 'Leveza extrema com apenas 990g. Ideal para produtividade em movimento, com chassi em fibra de carbono e teclado retroiluminado.', 'Notebooks', 8999, null, 4949.45, 15, 'SKU-NOTEBOOK-SLATE-AIR', null, array['https://picsum.photos/seed/slate-air-1/900/900', 'https://picsum.photos/seed/slate-air-2/900/900']::text[], false, true, false, true, 'Slate Air | Marvel', 'Leveza extrema com apenas 990g. Ideal para produtividade em movimento, com chassi em fibra de carbono e teclado retroiluminado.', 4.6, '2026-06-30'::timestamptz),
('phone-lumen-x', 'Lumen X', 'phone-lumen-x', 'Smartphone flagship com câmera tripla de 200MP, tela AMOLED de 6.7'''' e carregamento ultrarrápido de 120W.', 'Smartphone flagship com câmera tripla de 200MP, tela AMOLED de 6.7'''' e carregamento ultrarrápido de 120W.', 'Smartphones', 6499, 7299, 3574.45, 18, 'SKU-PHONE-LUMEN-X', null, array['https://picsum.photos/seed/lumen-x-1/900/900', 'https://picsum.photos/seed/lumen-x-2/900/900', 'https://picsum.photos/seed/lumen-x-3/900/900']::text[], true, false, true, true, 'Lumen X | Marvel', 'Smartphone flagship com câmera tripla de 200MP, tela AMOLED de 6.7'''' e carregamento ultrarrápido de 120W.', 4.7, '2026-04-18'::timestamptz),
('phone-lumen-mini', 'Lumen Mini', 'phone-lumen-mini', 'Compacto e potente, com desempenho flagship em um corpo de 5.8''''.', 'Compacto e potente, com desempenho flagship em um corpo de 5.8''''. Perfeito para quem prefere praticidade sem abrir mão de qualidade.', 'Smartphones', 4299, null, 2364.45, 22, 'SKU-PHONE-LUMEN-MINI', null, array['https://picsum.photos/seed/lumen-mini-1/900/900', 'https://picsum.photos/seed/lumen-mini-2/900/900']::text[], false, true, false, true, 'Lumen Mini | Marvel', 'Compacto e potente, com desempenho flagship em um corpo de 5.8''''. Perfeito para quem prefere praticidade sem abrir mão de qualidade.', 4.4, '2026-07-05'::timestamptz),
('watch-pulse-2', 'Pulse Watch 2', 'watch-pulse-2', 'Smartwatch com monitoramento avançado de saúde, GPS integrado e tela AMOLED sempre ativa.', 'Smartwatch com monitoramento avançado de saúde, GPS integrado e tela AMOLED sempre ativa. Resistente à água até 50m.', 'Wearables', 2299, 2599, 1264.45, 30, 'SKU-WATCH-PULSE-2', null, array['https://picsum.photos/seed/pulse-2-1/900/900', 'https://picsum.photos/seed/pulse-2-2/900/900']::text[], true, false, true, true, 'Pulse Watch 2 | Marvel', 'Smartwatch com monitoramento avançado de saúde, GPS integrado e tela AMOLED sempre ativa. Resistente à água até 50m.', 4.6, '2026-02-14'::timestamptz),
('band-fit-track', 'FitTrack Band', 'band-fit-track', 'Pulseira inteligente leve e discreta, com bateria de 10 dias e acompanhamento completo de sono e atividades.', 'Pulseira inteligente leve e discreta, com bateria de 10 dias e acompanhamento completo de sono e atividades.', 'Wearables', 549, null, 301.95, 55, 'SKU-BAND-FIT-TRACK', null, array['https://picsum.photos/seed/fittrack-1/900/900', 'https://picsum.photos/seed/fittrack-2/900/900']::text[], false, false, false, true, 'FitTrack Band | Marvel', 'Pulseira inteligente leve e discreta, com bateria de 10 dias e acompanhamento completo de sono e atividades.', 4.2, '2026-01-22'::timestamptz),
('monitor-horizon-32', 'Horizon 32 4K', 'monitor-horizon-32', 'Monitor 4K de 32'''' com HDR1000, 144Hz e cobertura de 98% do DCI-P3.', 'Monitor 4K de 32'''' com HDR1000, 144Hz e cobertura de 98% do DCI-P3. Perfeito para design, vídeo e jogos.', 'Monitores', 4599, null, 2529.45, 12, 'SKU-MONITOR-HORIZON-32', null, array['https://picsum.photos/seed/horizon-32-1/900/900', 'https://picsum.photos/seed/horizon-32-2/900/900']::text[], true, false, false, true, 'Horizon 32 4K | Marvel', 'Monitor 4K de 32'''' com HDR1000, 144Hz e cobertura de 98% do DCI-P3. Perfeito para design, vídeo e jogos.', 4.8, '2026-05-28'::timestamptz),
('monitor-flow-27', 'Flow 27 QHD', 'monitor-flow-27', 'Monitor QHD de 27'''' com 165Hz, ideal para produtividade e jogos competitivos.', 'Monitor QHD de 27'''' com 165Hz, ideal para produtividade e jogos competitivos. Ajuste de altura e rotação inclusos.', 'Monitores', 2199, 2499, 1209.45, 20, 'SKU-MONITOR-FLOW-27', null, array['https://picsum.photos/seed/flow-27-1/900/900', 'https://picsum.photos/seed/flow-27-2/900/900']::text[], false, true, true, true, 'Flow 27 QHD | Marvel', 'Monitor QHD de 27'''' com 165Hz, ideal para produtividade e jogos competitivos. Ajuste de altura e rotação inclusos.', 4.5, '2026-07-15'::timestamptz),
('acc-charge-dock', 'Charge Dock Trio', 'acc-charge-dock', 'Estação de carregamento 3 em 1 para smartphone, fone e smartwatch.', 'Estação de carregamento 3 em 1 para smartphone, fone e smartwatch. Carregamento sem fio de até 15W por dispositivo.', 'Acessórios', 449, null, 246.95, 60, 'SKU-ACC-CHARGE-DOCK', null, array['https://picsum.photos/seed/charge-dock-1/900/900', 'https://picsum.photos/seed/charge-dock-2/900/900']::text[], false, false, false, true, 'Charge Dock Trio | Marvel', 'Estação de carregamento 3 em 1 para smartphone, fone e smartwatch. Carregamento sem fio de até 15W por dispositivo.', 4.3, '2026-03-19'::timestamptz),
('acc-keyboard-mech', 'Mech Keyboard Zero', 'acc-keyboard-mech', 'Teclado mecânico compacto com switches hot-swap, retroiluminação RGB e conexão tripla (Bluetooth, 2.4GHz e USB-C).', 'Teclado mecânico compacto com switches hot-swap, retroiluminação RGB e conexão tripla (Bluetooth, 2.4GHz e USB-C).', 'Acessórios', 899, 999, 494.45, 34, 'SKU-ACC-KEYBOARD-MECH', null, array['https://picsum.photos/seed/mech-kb-1/900/900', 'https://picsum.photos/seed/mech-kb-2/900/900']::text[], true, true, true, true, 'Mech Keyboard Zero | Marvel', 'Teclado mecânico compacto com switches hot-swap, retroiluminação RGB e conexão tripla (Bluetooth, 2.4GHz e USB-C).', 4.7, '2026-07-01'::timestamptz),
('acc-mouse-glide', 'Glide Mouse', 'acc-mouse-glide', 'Mouse ergonômico sem fio com sensor de alta precisão de 4000 DPI e bateria recarregável de longa duração.', 'Mouse ergonômico sem fio com sensor de alta precisão de 4000 DPI e bateria recarregável de longa duração.', 'Acessórios', 349, null, 191.95, 48, 'SKU-ACC-MOUSE-GLIDE', null, array['https://picsum.photos/seed/glide-mouse-1/900/900', 'https://picsum.photos/seed/glide-mouse-2/900/900']::text[], false, false, false, true, 'Glide Mouse | Marvel', 'Mouse ergonômico sem fio com sensor de alta precisão de 4000 DPI e bateria recarregável de longa duração.', 4.4, '2026-02-08'::timestamptz),
('acc-backpack-city', 'City Backpack', 'acc-backpack-city', 'Mochila minimalista à prova d''água com compartimento acolchoado para notebook até 16'''' e porta USB externa.', 'Mochila minimalista à prova d''água com compartimento acolchoado para notebook até 16'''' e porta USB externa.', 'Acessórios', 599, null, 329.45, 27, 'SKU-ACC-BACKPACK-CITY', null, array['https://picsum.photos/seed/city-backpack-1/900/900', 'https://picsum.photos/seed/city-backpack-2/900/900']::text[], false, false, false, true, 'City Backpack | Marvel', 'Mochila minimalista à prova d''água com compartimento acolchoado para notebook até 16'''' e porta USB externa.', 4.6, '2026-04-04'::timestamptz),
('fone-studio-max', 'Studio Max', 'fone-studio-max', 'Headphone over-ear de estúdio com drivers de 50mm, resposta de frequência ampliada e almofadas em memory foam.', 'Headphone over-ear de estúdio com drivers de 50mm, resposta de frequência ampliada e almofadas em memory foam.', 'Fones', 2499, null, 1374.45, 10, 'SKU-FONE-STUDIO-MAX', null, array['https://picsum.photos/seed/studio-max-1/900/900', 'https://picsum.photos/seed/studio-max-2/900/900']::text[], false, false, false, true, 'Studio Max | Marvel', 'Headphone over-ear de estúdio com drivers de 50mm, resposta de frequência ampliada e almofadas em memory foam.', 4.9, '2026-01-30'::timestamptz),
('phone-lumen-fold', 'Lumen Fold', 'phone-lumen-fold', 'Smartphone dobrável com tela interna de 7.6'''' e externa de 6.2''''.', 'Smartphone dobrável com tela interna de 7.6'''' e externa de 6.2''''. O futuro da mobilidade em um design ousado.', 'Smartphones', 11999, 12999, 6599.45, 6, 'SKU-PHONE-LUMEN-FOLD', null, array['https://picsum.photos/seed/lumen-fold-1/900/900', 'https://picsum.photos/seed/lumen-fold-2/900/900', 'https://picsum.photos/seed/lumen-fold-3/900/900']::text[], true, true, true, true, 'Lumen Fold | Marvel', 'Smartphone dobrável com tela interna de 7.6'''' e externa de 6.2''''. O futuro da mobilidade em um design ousado.', 4.6, '2026-07-25'::timestamptz),
('notebook-vortex-16-pro', 'Vortex 16 Pro', 'notebook-vortex-16-pro', 'Potência máxima para workflows profissionais: GPU dedicada, 32GB de RAM e tela mini-LED de 16''''.', 'Potência máxima para workflows profissionais: GPU dedicada, 32GB de RAM e tela mini-LED de 16''''.', 'Notebooks', 18999, null, 10449.45, 5, 'SKU-NOTEBOOK-VORTEX-16-PRO', null, array['https://picsum.photos/seed/vortex-16-1/900/900', 'https://picsum.photos/seed/vortex-16-2/900/900']::text[], false, false, false, true, 'Vortex 16 Pro | Marvel', 'Potência máxima para workflows profissionais: GPU dedicada, 32GB de RAM e tela mini-LED de 16''''.', 4.9, '2026-02-27'::timestamptz),
('watch-pulse-lite', 'Pulse Watch Lite', 'watch-pulse-lite', 'Versão essencial do Pulse Watch, com as principais métricas de saúde e até 7 dias de bateria, por um preço mais acessível.', 'Versão essencial do Pulse Watch, com as principais métricas de saúde e até 7 dias de bateria, por um preço mais acessível.', 'Wearables', 1199, 1399, 659.45, 38, 'SKU-WATCH-PULSE-LITE', null, array['https://picsum.photos/seed/pulse-lite-1/900/900', 'https://picsum.photos/seed/pulse-lite-2/900/900']::text[], false, false, true, true, 'Pulse Watch Lite | Marvel', 'Versão essencial do Pulse Watch, com as principais métricas de saúde e até 7 dias de bateria, por um preço mais acessível.', 4.3, '2026-03-11'::timestamptz)
on conflict (id) do nothing;
